# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
